// eslint-disable-next-line import/prefer-default-export
export const LIST_MERCHANT_BY_CLASSIFY = 'LIST_MERCHANT_BY_CLASSIFY';
export const GET_LIST_MERCHANT_BY_CLASSIFY_SUCCESS = 'GET_LIST_MERCHANT_BY_CLASSIFY_SUCCESS';
export const GET_LIST_MERCHANT_BY_CLASSIFY_FAILSE = 'GET_LIST_MERCHANT_BY_CLASSIFY_FAILSE';

export const LIST_FEE_MERCHANT_MCC = 'LIST_FEE_MERCHANT_MCC';
export const GET_LIST_FEE_MERCHANT_MCC_SUCCESS = 'GET_LIST_FEE_MERCHANT_MCC_SUCCESS';
export const GET_LIST_FEE_MERCHANT_MCC_FAILSE = 'GET_LIST_FEE_MERCHANT_MCC_FAILSE';

export const LIST_FEE_MERCHANT_BY_TYPE_CODE = 'LIST_FEE_MERCHANT_BY_TYPE_CODE';
export const GET_LIST_FEE_MERCHANT_BY_TYPE_CODE_SUCCESS = 'GET_LIST_FEE_MERCHANT_BY_TYPE_CODE_SUCCESS';
export const GET_LIST_FEE_MERCHANT_BY_TYPE_CODE_FAILSE = 'GET_LIST_FEE_MERCHANT_BY_TYPE_CODE_FAILSE';

export const LIST_FEE_MERCHANT_NAME_AND_TYPE_CODE = 'LIST_FEE_MERCHANT_NAME_AND_TYPE_CODE';

export const GET_INFO_GENERAL_MERCHANT = 'GET_INFO_GENERAL_MERCHANT';

export const GET_INFO_APPLY_MERCHANT = 'GET_INFO_APPLY_MERCHANT';

export const UPLOAD_MC_BY_FILE_EXCELL = 'UPLOAD_MC_BY_FILE_EXCELL';
export const UPLOAD_MC_BY_FILE_EXCELL_SUCCESS = 'UPLOAD_MC_BY_FILE_EXCELL_SUCCESS';
export const UPLOAD_MC_BY_FILE_EXCELL_FAILSE = 'UPLOAD_MC_BY_FILE_EXCELL_FAILSE';

export const STORE_LIST_MERCHANT_LOCAL = 'STORE_LIST_MERCHANT_LOCAL';

export const ADD_FEE_MERCHANT = 'ADD_FEE_MERCHANT';
export const ADD_FEE_MERCHANT_SUCCESS = 'ADD_FEE_MERCHANT_SUCCESS';
export const ADD_FEE_MERCHANT_FAILSE = 'ADD_FEE_MERCHANT_FAILSE';

export const VALIDATE_ADD_FEE_MERCHANT = 'VALIDATE_ADD_FEE_MERCHANT';
export const VALIDATE_ADD_FEE_MERCHANT_SUCCESS = 'VALIDATE_ADD_FEE_MERCHANT_SUCCESS';
export const VALIDATE_ADD_FEE_MERCHANT_FAILSE = 'VALIDATE_ADD_FEE_MERCHANT_FAILSE';


export const GET_INFO_GENERAL_MERCHANT_EDIT_PAGE = 'GET_INFO_GENERAL_MERCHANT_EDIT_PAGE';

export const GET_ARRAY_DATA_MERCHANT_AVAILABLE = 'GET_ARRAY_DATA_MERCHANT_AVAILABLE';

export const CHANGE_VALUE_APPLY_TYPE = 'CHANGE_VALUE_APPLY_TYPE';
