/* eslint-disable import/prefer-default-export */
export const LOAD_INFOR_MERCHANT_BEFORE_EDIT = 'LOAD_INFOR_MERCHANT_BEFORE_EDIT';

export const LOAD_INFOR_MERCHANT_BEFORE_SUCCESS = 'LOAD_INFOR_MERCHANT_BEFORE_EDIT_SUCCESS';

export const LOAD_INFOR_MERCHANT_BEFORE_FAILED = 'LOAD_INFOR_MERCHANT_BEFORE_EDIT_FAILED';

export const LOAD_FEE_CODE_BY_CLASSIFY = 'LOAD_FEE_CODE_BY_CLASSIFY';

export const LOAD_FEE_CODE_BY_CLASSIFY_SUCCESS = 'LOAD_FEE_CODE_BY_CLASSIFY_SUCCESS';

export const LOAD_FEE_CODE_BY_CLASSIFY_FAILED = 'LOAD_FEE_CODE_BY_CLASSIFY_FAILED';


export const UPDATE_FEE_MERCHANT = 'UPDATE_FEE_MERCHANT';

export const UPDATE_FEE_MERCHANT_SUCCESS = 'UPDATE_FEE_MERCHANT_SUCCESS';

export const UPDATE_FEE_MERCHANT_FAILED = 'UPDATE_FEE_MERCHANT_FAILED';

export const COME_BACK_LIST_MERCHANT_PAGE = 'COME_BACK_LIST_MERCHANT_PAGE';

export const RESET_IS_SUCCESS_VALUE_IN_EDIT_MERCHANT_REDUCER = 'RESET_IS_SUCCESS_VALUE_IN_EDIT_MERCHANT_REDUCER';
