// eslint-disable-next-line import/prefer-default-export
export const CLICK_ONE_BUTTON = 'CLICK_ONE_BUTTON';

export const LOAD_FEE_NAME_MERCHANT = 'LOAD_FEE_NAME_MERCHANT';

export const LOAD_FEE_NAME_MERCHANT_SUCCESS = 'LOAD_FEE_NAME_MERCHANT_SUCCESS';

export const LOAD_FEE_NAME_MERCHANT_FAILED = 'LOAD_FEE_NAME_MERCHANT_FAILED';

export const LOAD_TYPE_SOURCE = 'LOAD_TYPE_SOURCE';

export const LOAD_TYPE_SOURCE_SUCCESS = 'LOAD_TYPE_SOURCE_SUCCESS';

export const LOAD_TYPE_SOURCE_FAILED = 'LOAD_TYPE_SOURCE_FAILED';

export const LOAD_TYPE_CHANNEL = 'LOAD_TYPE_CHANNEL';

export const LOAD_TYPE_CHANNEL_SUCCESS = 'LOAD_TYPE_CHANNEL_SUCCESS';

export const LOAD_TYPE_CHANNEL_FAILED = 'LOAD_TYPE_CHANNEL_FAILED';

export const TEXT_MERCHANT_NAME = 'TEXT_MERCHANT_NAME';

export const TEXT_MERCHANT_NAME_SUCCESS = 'TEXT_MERCHANT_NAME_SUCCESS';

export const TEXT_MERCHANT_NAME_FAILED = 'TEXT_MERCHANT_NAME_FAILED';

export const LOAD_FEE_MERCHANT_STATUS = 'LOAD_FEE_MERCHANT_STATUS';

export const LOAD_FEE_MERCHANT_STATUS_SUCCESS = 'LOAD_FEE_MERCHANT_STATUS_SUCCESS';

export const LOAD_FEE_MERCHANT_STATUS_FAILED = 'LOAD_FEE_MERCHANT_STATUS_FAILED';

export const LOAD_TABLE = 'LOAD_TABLE';

export const LOAD_TABLE_SUCCESS = 'LOAD_TABLE_SUCCESS';

export const LOAD_TABLE_FAILED = 'LOAD_TABLE_FAILED';

export const SEARCH_FEE_MERCHANT_BUTTON = 'SEARCH_FEE_MERCHANT_BUTTON';

export const SEARCH_FEE_MERCHANT_BUTTON_SUCCESS = 'SEARCH_FEE_MERCHANT_SUCCESS';

export const SEARCH_FEE_MERCHANT_BUTTON_FAILED = 'SEARCH_FEE_MERCHANT_FAILED';

export const CLICK_CHANGE_ROW_PAGE = 'CLICK_CHANGE_ROW_PAGE';

export const CLICK_CHANGE_ROW_PAGE_SUCCESS = 'CLICK_CHANGE_ROW_PAGE_SUCCESS';

export const CLICK_CHANGE_ROW_PAGE_FAILED = 'CLICK_CHANGE_ROW_PAGE_FAILED';

export const CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE = 'CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE';

export const CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE_SUCCESS = 'CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE_SUCCESS';

export const CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE_FAILED = 'CLICK_TO_EXPORT_EXCEL_MERCHANT_LIST_FILE_FAILED';

export const
  CLICK_TO_EDIT_A_MERCHANT = 'CLICK_TO_EDIT_A_MERCHANT';


