
// eslint-disable-next-line import/prefer-default-export
export const CLASSIFY_SIGNING = 'CLASSIFY_SIGNING';
export const GET_CLASSIFY_SIGNING_SUCCESS = 'GET_CLASSIFY_SIGNING_SUCCESS';
export const GET_CLASSIFY_SIGNING_FAILSE = 'GET_CLASSIFY_SIGNING_FAILSE';

export const DENIED_DESC = 'DENIED_DESC';
export const LOAD_DENIED_DESC_SUCCESS = 'LOAD_DENIED_DESC_SUCCESS';
export const LOAD_DENIED_DESC_FAILED = 'LOAD_DENIED_DESC_FAILED';

export const FEE_STATUS = 'FEE_STATUS';
export const LOAD_FEE_STATUS_SUCCESS = 'LOAD_FEE_STATUS_SUCCESS';
export const LOAD_FEE_STATUS_FAILED = 'LOAD_FEE_STATUS_FAILED';

export const PAY_CHANNEL = 'PAY_CHANNEL';
export const LOAD_PAY_CHANNEL_SUCCESS = 'LOAD_PAY_CHANNEL_SUCCESS';
export const LOAD_PAY_CHANNEL_FAILED = 'LOAD_PAY_CHANNEL_FAILED';

export const TYPE_SOURCE = 'TYPE_SOURCE';
export const LOAD_TYPE_SOURCE_SUCCESS = 'LOAD_TYPE_SOURCE_SUCCESS';
export const LOAD_TYPE_SOURCE_FAILED = 'LOAD_TYPE_SOURCE_FAILED';

export const FOLOW_CAL = 'FOLOW_CAL';
export const LOAD_FOLOW_CAL_SUCCESS = 'LOAD_FOLOW_CAL_SUCCESS';
export const LOAD_FOLOW_CAL_FAILED = 'LOAD_FOLOW_CAL_FAILED';

export const CALCULATION_RULES = 'CALCULATION_RULES';
export const LOAD_CALCULATION_RULES_SUCCESS = 'LOAD_CALCULATION_RULES_SUCCESS';
export const LOAD_CALCULATION_RULES_FAILED = 'LOAD_CALCULATION_RULES_FAILED';

export const CALCULATION_FORM = 'CALCULATION_FORM';
export const LOAD_CALCULATION_FORM_SUCCESS = 'CALCULATION_FORM_SUCCESS';
export const LOAD_CALCULATION_FORM_FAILED = 'LOAD_CALCULATION_FORM_FAILED';

export const APPLY_TYPE_MERCHANT = 'APPLY_TYPE_MERCHANT';
export const APPLY_TYPE_MERCHANT_SUCCESS = 'APPLY_TYPE_MERCHANT_SUCCESS';
export const APPLY_TYPE_MERCHANT_FAILED = 'APPLY_TYPE_MERCHANT_FAILED';

export const LIST_BANKS = 'LIST_BANKS';
export const LIST_BANKS_SUCCESS = 'LIST_BANKS_SUCCESS';
export const LIST_BANKS_FAILED = 'LIST_BANKS_FAILED';

export const LIST_MCC = 'LIST_MCC';
export const LIST_MCC_SUCCESS = 'LIST_MCC_SUCCESS';
export const LIST_MCC_FAILED = 'LIST_MCC_FAILED';

export const FEE_CODE_FEE_NAME_VMMS = 'FEE_CODE_FEE_NAME_VMMS';
export const FEE_CODE_FEE_NAME_VMMS_SUCCESS = 'FEE_CODE_FEE_NAME_VMMS_SUCCESS';
export const FEE_CODE_FEE_NAME_VMMS_FAILED = 'FEE_CODE_FEE_NAME_VMMS_FAILED';

export const ADD_MCC_NATIONAL = 'ADD_MCC_NATIONAL';
export const REMOVE_MCC_NATIONAL = 'REMOVE_MCC_NATIONAL';
export const APPLY_MCC_NATIONAL = 'APPLY_MCC_NATIONAL';

export const TOGGLE_ACTION = 'TOGGLE_ACTION';
