export const APPROVE_LIST_MERCHANT = 'APPROVE_LIST_MERCHANT';
export const APPROVE_LIST_MERCHANT_SUCCESS = 'APPROVE_LIST_MERCHANT_SUCCESS';
export const APPROVE_LIST_MERCHANT_FAILED = 'APPROVE_LIST_MERCHANT_FAILED';
