
// eslint-disable-next-line import/prefer-default-export
export const LOAD_REASON_FOR_REFUSE_MERCHANT = 'LOAD_REASON_FOR_REFUSE_MERCHANT';
export const LOAD_REASON_FOR_REFUSE_MERCHANT_SUCCESS = 'LOAD_REASON_FOR_REFUSE_MERCHANT_SUCCESS';
export const LOAD_REASON_FOR_REFUSE_MERCHANT_FAILED = 'LOAD_REASON_FOR_REFUSE_MERCHANT_FAILED';

export const LOAD_LIST_MERCHANT_DETAIL = 'LOAD_LIST_MERCHANT_DETAIL';
export const LOAD_LIST_MERCHANT_DETAIL_SUCCESS = 'LOAD_LIST_MERCHANT_DETAIL_SUCCESS';
export const LOAD_LIST_MERCHANT_DETAIL_FAILED = 'LOAD_LIST_MERCHANT_DETAIL_FAILED';
