/* eslint-disable import/prefer-default-export */

export const CLICK_TO_OPEN_MODAL = 'CLICK_TO_OPEN_MODAL';

export const CLICK_TO_CLOSE_MODAL = 'CLICK_TO_CLOSE_MODAL';

export const CLICK_TO_LOCK_IN_MODAL = 'CLICK_TO_LOCK_IN_MODAL';

export const CLICK_TO_LOCK_IN_MODAL_SUCCESS = 'CLICK_TO_LOCK_IN_MODAL_SUCCESS';

export const CLICK_TO_LOCK_IN_MODAL_FAILED = 'CLICK_TO_LOCK_IN_MODAL_FAILED';


export const CLICK_TO_UNLOCK_MODAL = 'CLICK_TO_UNLOCK_MODAL';

export const CLICK_TO_UNLOCK_MODAL_SUCCESS = 'CLICK_TO_UNLOCK_MODAL_SUCCESS';

export const CLICK_TO_UNLOCK_MODAL_FAILED = 'CLICK_TO_UNLOCK_MODAL_FAILED';

export const CLICK_TO_OPEN_MODAL_UNLOCK = 'CLICK_TO_OPEN_MODAL_UNLOCK';

export const CLICK_TO_LOCK_MERCHANT_IN_EDIT = 'CLICK_TO_LOCK_MERCHANT_IN_EDIT';

export const CLICK_TO_LOCK_MERCHANT_IN_EDIT_SUCCESS = 'CLICK_TO_LOCK_MERCHANT_IN_EDIT_SUCCESS';

export const CLICK_TO_LOCK_MERCHANT_IN_EDIT_FAILED = 'CLICK_TO_LOCK_MERCHANT_IN_EDIT_FAILED';


export const CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT = 'CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT';

export const CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT_SUCCESS = 'CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT_SUCCESS';

export const CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT_FAILED = 'CLICK_TO_UN_LOCK_MERCHANT_IN_EDIT_FAILED';

