export const GET_MASTER_MERCHANT = 'GET_MASTER_MERCHANT';

export const GET_MASTER_MERCHANT_SUCCESS = 'GET_MASTER_MERCHANT_SUCCESS';

export const GET_MASTER_MERCHANT_FAILED = 'GET_MASTER_MERCHANT_FAILED';


export const GET_FEE_CODE = 'GET_FEE_CODE';

export const GET_FEE_CODE_SUCCESS = 'GET_FEE_CODE_SUCCESS';

export const GET_FEE_CODE_FAILED = 'GET_FEE_CODE_FAILED';

export const GET_STATUS = 'GET_STATUS';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';

export const GET_STATUS_FAILED = 'GET_STATUS_FAILED';

export const GET_ALL_MCC = 'GET_ALL_MCC';

export const GET_ALL_MCC_SUCCESS = 'GET_ALL_MCC_SUCCESS';

export const GET_ALL_MCC_FAILED = 'GET_ALL_MCC_FAILED';

